import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import Carousel from "@/components/carousel";
import OurClient from "@/components/our-client";
import Features from "@/components/feature/feature-section";
import Overview from "@/components/overview/overview-section";
import Banner from "@/components/banner";
import { heroThree, heroTwo } from "@/data/features";
import Testimonial from "@/components/testimonial";
import FAQ from "@/components/faq/faq-section";
import Demo from "@/components/demo";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Nexcent</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Navbar />
        <Carousel />
        <OurClient />
        <Features />
        <Banner data={heroTwo} />
        <Overview />
        <Banner data={heroThree} />
        <Testimonial />
        <FAQ />
        <Demo />
        <Footer />
      </main>
    </>
  );
}
